# Generated by Django 4.2.3 on 2023-11-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='full_name',
        ),
    ]
