# Generated by Django 4.2.3 on 2023-11-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_useraccount_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
