# Generated by Django 4.2.3 on 2023-11-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_useraccount_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
