# Generated by Django 4.2.3 on 2023-11-08 10:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_useraccount_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[core.models.no_email_validation], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='full_name',
            field=models.CharField(default=1, max_length=150, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='username'),
        ),
    ]
