# Generated by Django 4.2.3 on 2023-11-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_reviewmodule_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodule',
            name='request_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodule',
            name='review_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
