# Generated by Django 4.2.3 on 2023-11-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_requestmodule_request_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodule',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
