# Generated by Django 4.2.3 on 2023-11-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_requestmodule_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodule',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
