# Generated by Django 4.2.3 on 2023-12-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_reviewmodule_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastermodule',
            name='comment_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
