# Generated by Django 4.2.3 on 2023-12-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_mastermodule_comment_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodule',
            name='add_note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
