# Generated by Django 4.2.3 on 2023-12-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_requestmodule_add_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmodule',
            name='add_note',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
